/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DemoLegendStateImport } from './routes/demo.legend-state'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoLegendStateRoute = DemoLegendStateImport.update({
  id: '/demo/legend-state',
  path: '/demo/legend-state',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo/legend-state': {
      id: '/demo/legend-state'
      path: '/demo/legend-state'
      fullPath: '/demo/legend-state'
      preLoaderRoute: typeof DemoLegendStateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/legend-state': typeof DemoLegendStateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/legend-state': typeof DemoLegendStateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo/legend-state': typeof DemoLegendStateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/legend-state'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/legend-state'
  id: '__root__' | '/' | '/demo/legend-state'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoLegendStateRoute: typeof DemoLegendStateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoLegendStateRoute: DemoLegendStateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo/legend-state"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo/legend-state": {
      "filePath": "demo.legend-state.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
