blank_issues_enabled: false
contact_links:
  - name: 💬 Community Chat
    url: https://discord.gg/mQd7egN
    about: A dedicated discord server hosted by Tanner Linsley
  - name: 💬 Tanstack Twitter
    url: https://twitter.com/tan_stack
    about: Stay up to date with new releases of our libraries
