/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MotorcyclesMotorcycleIdImport } from './routes/motorcycles/$motorcycleId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MotorcyclesMotorcycleIdRoute = MotorcyclesMotorcycleIdImport.update({
  id: '/motorcycles/$motorcycleId',
  path: '/motorcycles/$motorcycleId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/motorcycles/$motorcycleId': {
      id: '/motorcycles/$motorcycleId'
      path: '/motorcycles/$motorcycleId'
      fullPath: '/motorcycles/$motorcycleId'
      preLoaderRoute: typeof MotorcyclesMotorcycleIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/motorcycles/$motorcycleId': typeof MotorcyclesMotorcycleIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/motorcycles/$motorcycleId': typeof MotorcyclesMotorcycleIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/motorcycles/$motorcycleId': typeof MotorcyclesMotorcycleIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/motorcycles/$motorcycleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/motorcycles/$motorcycleId'
  id: '__root__' | '/' | '/motorcycles/$motorcycleId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MotorcyclesMotorcycleIdRoute: typeof MotorcyclesMotorcycleIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MotorcyclesMotorcycleIdRoute: MotorcyclesMotorcycleIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/motorcycles/$motorcycleId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/motorcycles/$motorcycleId": {
      "filePath": "motorcycles/$motorcycleId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
